// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {frontend} from '../models';

export function AddEntity(arg1:string):Promise<main.Entity>;

export function AddEntityType(arg1:string):Promise<main.EntityType>;

export function AddRelationType(arg1:string):Promise<main.RelationType>;

export function AddRelationship(arg1:string):Promise<main.Relationship>;

export function ClearData():Promise<void>;

export function ClearHistory():Promise<void>;

export function ClusterAnalysis():Promise<main.ClusterResult>;

export function ConnectNeuroDB(arg1:string,arg2:number):Promise<string>;

export function DeleteEntity(arg1:string):Promise<boolean>;

export function DeleteRelationship(arg1:string):Promise<boolean>;

export function ExportJSONData():Promise<string>;

export function GetEntityTypes():Promise<Array<main.EntityType>>;

export function GetGraphData():Promise<main.GraphData>;

export function GetHistory():Promise<Array<main.HistoryEntry>>;

export function GetNeuroDBInfo():Promise<string>;

export function GetNeuroDBStatus():Promise<main.NeuroDBStatus>;

export function GetRecentHistory(arg1:number):Promise<Array<main.HistoryEntry>>;

export function GetRelationTypes():Promise<Array<main.RelationType>>;

export function ImportCSVEntities(arg1:string):Promise<main.GraphData>;

export function ImportCSVEntitiesReplace(arg1:string):Promise<main.GraphData>;

export function ImportCSVRelationships(arg1:string):Promise<main.GraphData>;

export function ImportCSVRelationshipsReplace(arg1:string):Promise<main.GraphData>;

export function ImportJSONData(arg1:string):Promise<main.GraphData>;

export function ImportJSONDataReplace(arg1:string):Promise<main.GraphData>;

export function LinkAnalysis(arg1:string,arg2:number):Promise<main.LinkAnalysisResult>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function PathAnalysis(arg1:string,arg2:string):Promise<main.PathResult>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;

export function SocialNetworkAnalysis():Promise<main.SNAResult>;

export function StartNeuroDB():Promise<string>;

export function StopNeuroDB():Promise<string>;

export function SyncToNeuroDB():Promise<string>;

export function UpdateEntity(arg1:string):Promise<main.Entity>;

export function UpdateRelationship(arg1:string):Promise<main.Relationship>;

export function WriteBase64File(arg1:string,arg2:string):Promise<boolean>;

export function WriteFile(arg1:string,arg2:string):Promise<boolean>;
