// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntity(arg1) {
  return window['go']['main']['App']['AddEntity'](arg1);
}

export function AddEntityType(arg1) {
  return window['go']['main']['App']['AddEntityType'](arg1);
}

export function AddRelationType(arg1) {
  return window['go']['main']['App']['AddRelationType'](arg1);
}

export function AddRelationship(arg1) {
  return window['go']['main']['App']['AddRelationship'](arg1);
}

export function ClearData() {
  return window['go']['main']['App']['ClearData']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClusterAnalysis() {
  return window['go']['main']['App']['ClusterAnalysis']();
}

export function ConnectNeuroDB(arg1, arg2) {
  return window['go']['main']['App']['ConnectNeuroDB'](arg1, arg2);
}

export function DeleteEntity(arg1) {
  return window['go']['main']['App']['DeleteEntity'](arg1);
}

export function DeleteRelationship(arg1) {
  return window['go']['main']['App']['DeleteRelationship'](arg1);
}

export function ExportJSONData() {
  return window['go']['main']['App']['ExportJSONData']();
}

export function GetEntityTypes() {
  return window['go']['main']['App']['GetEntityTypes']();
}

export function GetGraphData() {
  return window['go']['main']['App']['GetGraphData']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetNeuroDBInfo() {
  return window['go']['main']['App']['GetNeuroDBInfo']();
}

export function GetNeuroDBStatus() {
  return window['go']['main']['App']['GetNeuroDBStatus']();
}

export function GetRecentHistory(arg1) {
  return window['go']['main']['App']['GetRecentHistory'](arg1);
}

export function GetRelationTypes() {
  return window['go']['main']['App']['GetRelationTypes']();
}

export function ImportCSVEntities(arg1) {
  return window['go']['main']['App']['ImportCSVEntities'](arg1);
}

export function ImportCSVEntitiesReplace(arg1) {
  return window['go']['main']['App']['ImportCSVEntitiesReplace'](arg1);
}

export function ImportCSVRelationships(arg1) {
  return window['go']['main']['App']['ImportCSVRelationships'](arg1);
}

export function ImportCSVRelationshipsReplace(arg1) {
  return window['go']['main']['App']['ImportCSVRelationshipsReplace'](arg1);
}

export function ImportJSONData(arg1) {
  return window['go']['main']['App']['ImportJSONData'](arg1);
}

export function ImportJSONDataReplace(arg1) {
  return window['go']['main']['App']['ImportJSONDataReplace'](arg1);
}

export function LinkAnalysis(arg1, arg2) {
  return window['go']['main']['App']['LinkAnalysis'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function PathAnalysis(arg1, arg2) {
  return window['go']['main']['App']['PathAnalysis'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SocialNetworkAnalysis() {
  return window['go']['main']['App']['SocialNetworkAnalysis']();
}

export function StartNeuroDB() {
  return window['go']['main']['App']['StartNeuroDB']();
}

export function StopNeuroDB() {
  return window['go']['main']['App']['StopNeuroDB']();
}

export function SyncToNeuroDB() {
  return window['go']['main']['App']['SyncToNeuroDB']();
}

export function UpdateEntity(arg1) {
  return window['go']['main']['App']['UpdateEntity'](arg1);
}

export function UpdateRelationship(arg1) {
  return window['go']['main']['App']['UpdateRelationship'](arg1);
}

export function WriteBase64File(arg1, arg2) {
  return window['go']['main']['App']['WriteBase64File'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
